server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store-service/**
            - Method=GET,POST
          filters:
            - RewritePath=/store-service/(?<segment>.*), /$\{segment}
