spring:
  messages:
    basename: messages.validation
  profiles:
    group:
      prod:
        - prod
        - hide
      dev:
        - dev
        - hide
      test:
        - test
        - testhide
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  redis:
    port: 6379 #설정한 포트번호
    host: 127.0.0.1
  cache:
    redis:
      time-to-live: 86400000 # 1초

  # Multipart 설정
  servlet:
    multipart:
      max-file-size: 100MB # 요청한 파일 한 개의 크기
      max-request-size: 100MB # 요청한 파일 전체의 크기

management:
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  tomcat:
    mbeanregistry:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


store:
  pageNum: 10


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
