name: baedal BE server CI/CD

on:
  push:
    branches: [ dev-BE ]
  pull_request:
    branches: [ dev-BE ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
      S3_BUCKET_NAME: baedal-deploy

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Copy Secret
      env:
        OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
        OCCUPY_SECRET_DIR: src/main/resources
        OCCUPY_SECRET_DIR_FILE_NAME: application-hide.yml
      run: echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
      working-directory: ${{ env.working-directory }}
      
    - name: Build with Gradle
      run: ./gradlew clean build
      working-directory: ${{ env.working-directory }}
      
    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
      working-directory: ${{ env.working-directory }}
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy
      working-directory: ${{ env.working-directory }}
      
    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy
      working-directory: ${{ env.working-directory }}


    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy
      working-directory: ${{ env.working-directory }}

    - name: Make zip file
      run: zip -r ./baedal.zip ./deploy
      shell: bash
      working-directory: ${{ env.working-directory }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./baedal.zip s3://$S3_BUCKET_NAME/
      working-directory: ${{ env.working-directory }}
      
    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment --application-name baedal --deployment-group-name baedal-group --file-exists-behavior OVERWRITE --s3-location bucket=baedal-deploy,bundleType=zip,key=baedal.zip --region ap-northeast-2
